version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: host.docker.internal # apunta a tu PC desde Docker
      DB_USER: elsen
      DB_PASSWORD: mateinelpr7
      DB_NAME: tiendDB # tu base existente
      DB_PORT: 3306 # el puerto de Workbench
      PORT: 3001
    working_dir: /app
    command: ["npm", "start"]

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
